export const CODICI_PAGAMENTO = [
  { cod: "S01", desc: "Rimessa diretta POS" },
  { cod: "BO02", desc: "Bonifico 60 gg. d.f. f.m." },
  { cod: "BO18", desc: "Bonifico 30/60 gg. d.f." },
  { cod: "RB23", desc: "R.B. 90 gg. d.f. f.m." },
  { cod: "RD01", desc: "Rimessa diretta vista fattura contanti" },
  { cod: "S10", desc: "Rimessa diretta contanti CASOREZZO" },
  { cod: "BO05", desc: "Bonifico 30 gg. d.f. f.m." },
  { cod: "RB22", desc: "R.B. 60 gg. d.f. f.m." },
  { cod: "RB21", desc: "R.B. 30 gg. d.f. f.m." },
  { cod: "BO10", desc: "Bonifico bancario vista fattura" },
  { cod: "RB09", desc: "R.B. 60 gg. d.f. f.m. 10 ms" },
  { cod: "RB26", desc: "R.B. 60/90 gg. d.f. f.m." },
  { cod: "RB12", desc: "R.B. 90 gg. d.f. f.m. 10 ms" },
  { cod: "RB25", desc: "R.B. 30/60 gg. d.f. f.m." },
  { cod: "RB05", desc: "R.B. 60 gg d.f. 10 ms" },
  { cod: "BOS", desc: "Bonifico bancario vista fattura S" },
  { cod: "S11", desc: "Rimessa diretta contanti LISSONE" },
  { cod: "BO04", desc: "Bonifico 60 gg. d.f. f.m. 10 ms" },
  { cod: "RB29", desc: "R.B. 60/90/120 gg. d.f. f.m." },
  { cod: "RB11", desc: "R.B. 90 gg. d.f. 5 ms" },
  { cod: "RB38", desc: "R.B. 60/90 gg. d.f. 10 ms" },
  { cod: "RB69", desc: "R.B. 30 gg. d.f. f.m. 10 ms" },
  { cod: "S14", desc: "Rimessa diretta contanti AFFORI" },
  { cod: "BO03", desc: "Bonifico 90 gg. d.f. f.m." },
  { cod: "BO06", desc: "Bonifico 150 gg. d.f. f.m." },
  { cod: "RB28", desc: "R.B. 30/60/90 gg. d.f. f.m." },
  { cod: "S12", desc: "Rimessa diretta contanti CAMBIAGO" },
  { cod: "RD02", desc: "Rimessa diretta vista fattura assegno" },
  { cod: "RB01", desc: "R.B. 30 gg. d.f. 10 ms" },
  { cod: "RB10", desc: "R.B. 60 gg. d.f. f.m. 15 ms" },
  { cod: "RB86", desc: "R.B. 30/60/90 gg. d.f. 10 ms" },
  { cod: "BO07", desc: "Bonifico 90 gg. d.f. f.m. 10 ms" },
  { cod: "RB37", desc: "R.B. 60/90 gg. d.f. f.m. 10 ms" },
  { cod: "BO09", desc: "Bonifico 60 gg. d.f. f.m. 15 ms" },
  { cod: "RB27", desc: "R.B. 90/120 gg. d.f. f.m." },
  { cod: "RB15", desc: "R.B. 120 gg. d.f. f.m. 10 ms" },
  { cod: "RB24", desc: "R.B. 120 gg. d.f. f.m." },
  { cod: "RB02", desc: "R.B. 60 gg. d.f." },
  { cod: "S13", desc: "Rimessa diretta contanti PIANEZZA" },
  { cod: "AV56", desc: "Rimessa diretta vista fattura ***" },
  { cod: "S51", desc: "Rimessa diretta assegno LISSONE" },
  { cod: "S02", desc: "Bonifico" },
  { cod: "S50", desc: "Rimessa diretta assegno CASOREZZO" },
  { cod: "RD03", desc: "Rimessa diretta da finanziaria" },
  { cod: "O01", desc: "ON-LINE carta di credito" },
  { cod: "BO13", desc: "Bonifico 30/60 gg. d.f. f.m." },
  { cod: "S52", desc: "Rimessa diretta assegno CAMBIAGO" },
  { cod: "BO11", desc: "Bonifico 30 gg. d.f. f.m. 10 ms" },
  { cod: "RB13", desc: "R.B. 120 gg. d.f. 5 ms" },
  { cod: "RB41", desc: "R.B. 30/60 gg. d.f. 10ms" },
  { cod: "S53", desc: "Rimessa diretta assegno PIANEZZA" },
  { cod: "BO15", desc: "Bonifico 90/120 gg. d.f. f.m." },
  { cod: "RB30", desc: "R.B. 90/120/150 gg. d.f. f.m." },
  { cod: "BO14", desc: "Bonifico 120 gg. d.f. f.m." },
  { cod: "BO17", desc: "Bonifico 60/90/120 gg. d.f. f.m." },
  { cod: "RID04", desc: "RID vista fattura" },
  { cod: "RID07", desc: "RID 60 gg. d.f." },
  { cod: "S15", desc: "Rimessa diretta contanti CERIANO" },
  { cod: "RB19", desc: "R.B. 90/120 gg. d.f. f.m. 10 ms" },
  { cod: "S16", desc: "Rimessa diretta contanti VERCELLI" },
  { cod: "RB32", desc: "R.B. 30/60/90/120 gg. d.f. f.m." },
  { cod: "BO12", desc: "Bonifico 30/60/90 gg. d.f. f.m." },
  { cod: "S17", desc: "Rimessa diretta contanti CINISELLO" },
  { cod: "S18", desc: "Rimessa diretta contanti SAVIGLIANO" },
  { cod: "BO08", desc: "Bonifico 60/90 gg. d.f. f.m." },
  { cod: "RB35", desc: "R.B. 60 gg. d.f. f.m. 5 ms" },
  { cod: "S56", desc: "Rimessa diretta assegno VERCELLI" },
  { cod: "S58", desc: "Rimessa diretta assegno SAVIGLIANO" },
  { cod: "RB06", desc: "R.B. 60/90 gg. d.f." },
  { cod: "RB03", desc: "R.B. 90 gg. d.f." },
  { cod: "BO21", desc: "Bonifico 60/90 gg d.f. f.m. al 15 ms" },
  { cod: "RB84", desc: "R.B. 60/90 gg d.f. f.m. al 15 ms" },
  { cod: "RB64", desc: "R.B. 90 gg d.f. f.m. 15ms" },
  { cod: "BO22", desc: "Bonifico 30/60 gg. d.f.+15" },
  { cod: "RB73", desc: "R.B. 90 gg. d.f. 10 ms" },
] as const;

export type CodicePagamento = (typeof CODICI_PAGAMENTO)[number];

export function findCodicePagamento(cod: string): CodicePagamento | undefined {
  if (!cod) return undefined;
  const target = cod.trim().toUpperCase();
  return CODICI_PAGAMENTO.find((c) => c.cod.toUpperCase() === target);
}
