/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirmaPrivacyTokenRouteImport } from './routes/firma-privacy.$token'
import { Route as AppWhatsappRouteImport } from './routes/_app/whatsapp'
import { Route as AppUtentiRouteImport } from './routes/_app/utenti'
import { Route as AppTemplateEmailRouteImport } from './routes/_app/template-email'
import { Route as AppScadenziarioRouteImport } from './routes/_app/scadenziario'
import { Route as AppRichiesteRouteImport } from './routes/_app/richieste'
import { Route as AppRecuperoCreditiPromemoriaRouteImport } from './routes/_app/recupero-crediti-promemoria'
import { Route as AppRecuperoCreditiCampagneRouteImport } from './routes/_app/recupero-crediti-campagne'
import { Route as AppRecuperoCreditiCalendarioRouteImport } from './routes/_app/recupero-crediti-calendario'
import { Route as AppRecuperoCreditiAndamentoRouteImport } from './routes/_app/recupero-crediti-andamento'
import { Route as AppRecuperoCreditiRouteImport } from './routes/_app/recupero-crediti'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppLegaliRouteImport } from './routes/_app/legali'
import { Route as AppImpostazioniRouteImport } from './routes/_app/impostazioni'
import { Route as AppImportExportRouteImport } from './routes/_app/import-export'
import { Route as AppFidiProcessareRouteImport } from './routes/_app/fidi-processare'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContattiRouteImport } from './routes/_app/contatti'
import { Route as AppClientiRouteImport } from './routes/_app/clienti'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAssicurazioniRouteImport } from './routes/_app/assicurazioni'
import { Route as AppApprovazioniRouteImport } from './routes/_app/approvazioni'
import { Route as ApiPublicInngestRouteImport } from './routes/api/public/inngest'
import { Route as AppRichiesteRichiestaIdRouteImport } from './routes/_app/richieste.$richiestaId'
import { Route as AppClientiClienteIdRouteImport } from './routes/_app/clienti.$clienteId'
import { Route as ApiPublicHooksCheckScadenzeRouteImport } from './routes/api/public/hooks/check-scadenze'
import { Route as ApiPublicHooksCheckReminderRitardiRouteImport } from './routes/api/public/hooks/check-reminder-ritardi'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmaPrivacyTokenRoute = FirmaPrivacyTokenRouteImport.update({
  id: '/firma-privacy/$token',
  path: '/firma-privacy/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppUtentiRoute = AppUtentiRouteImport.update({
  id: '/utenti',
  path: '/utenti',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplateEmailRoute = AppTemplateEmailRouteImport.update({
  id: '/template-email',
  path: '/template-email',
  getParentRoute: () => AppRoute,
} as any)
const AppScadenziarioRoute = AppScadenziarioRouteImport.update({
  id: '/scadenziario',
  path: '/scadenziario',
  getParentRoute: () => AppRoute,
} as any)
const AppRichiesteRoute = AppRichiesteRouteImport.update({
  id: '/richieste',
  path: '/richieste',
  getParentRoute: () => AppRoute,
} as any)
const AppRecuperoCreditiPromemoriaRoute =
  AppRecuperoCreditiPromemoriaRouteImport.update({
    id: '/recupero-crediti-promemoria',
    path: '/recupero-crediti-promemoria',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecuperoCreditiCampagneRoute =
  AppRecuperoCreditiCampagneRouteImport.update({
    id: '/recupero-crediti-campagne',
    path: '/recupero-crediti-campagne',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecuperoCreditiCalendarioRoute =
  AppRecuperoCreditiCalendarioRouteImport.update({
    id: '/recupero-crediti-calendario',
    path: '/recupero-crediti-calendario',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecuperoCreditiAndamentoRoute =
  AppRecuperoCreditiAndamentoRouteImport.update({
    id: '/recupero-crediti-andamento',
    path: '/recupero-crediti-andamento',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecuperoCreditiRoute = AppRecuperoCreditiRouteImport.update({
  id: '/recupero-crediti',
  path: '/recupero-crediti',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppLegaliRoute = AppLegaliRouteImport.update({
  id: '/legali',
  path: '/legali',
  getParentRoute: () => AppRoute,
} as any)
const AppImpostazioniRoute = AppImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AppRoute,
} as any)
const AppImportExportRoute = AppImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => AppRoute,
} as any)
const AppFidiProcessareRoute = AppFidiProcessareRouteImport.update({
  id: '/fidi-processare',
  path: '/fidi-processare',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContattiRoute = AppContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => AppRoute,
} as any)
const AppClientiRoute = AppClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssicurazioniRoute = AppAssicurazioniRouteImport.update({
  id: '/assicurazioni',
  path: '/assicurazioni',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovazioniRoute = AppApprovazioniRouteImport.update({
  id: '/approvazioni',
  path: '/approvazioni',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicInngestRoute = ApiPublicInngestRouteImport.update({
  id: '/api/public/inngest',
  path: '/api/public/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRichiesteRichiestaIdRoute = AppRichiesteRichiestaIdRouteImport.update({
  id: '/$richiestaId',
  path: '/$richiestaId',
  getParentRoute: () => AppRichiesteRoute,
} as any)
const AppClientiClienteIdRoute = AppClientiClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => AppClientiRoute,
} as any)
const ApiPublicHooksCheckScadenzeRoute =
  ApiPublicHooksCheckScadenzeRouteImport.update({
    id: '/api/public/hooks/check-scadenze',
    path: '/api/public/hooks/check-scadenze',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckReminderRitardiRoute =
  ApiPublicHooksCheckReminderRitardiRouteImport.update({
    id: '/api/public/hooks/check-reminder-ritardi',
    path: '/api/public/hooks/check-reminder-ritardi',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/approvazioni': typeof AppApprovazioniRoute
  '/assicurazioni': typeof AppAssicurazioniRoute
  '/audit': typeof AppAuditRoute
  '/clienti': typeof AppClientiRouteWithChildren
  '/contatti': typeof AppContattiRoute
  '/dashboard': typeof AppDashboardRoute
  '/fidi-processare': typeof AppFidiProcessareRoute
  '/import-export': typeof AppImportExportRoute
  '/impostazioni': typeof AppImpostazioniRoute
  '/legali': typeof AppLegaliRoute
  '/privacy': typeof AppPrivacyRoute
  '/recupero-crediti': typeof AppRecuperoCreditiRoute
  '/recupero-crediti-andamento': typeof AppRecuperoCreditiAndamentoRoute
  '/recupero-crediti-calendario': typeof AppRecuperoCreditiCalendarioRoute
  '/recupero-crediti-campagne': typeof AppRecuperoCreditiCampagneRoute
  '/recupero-crediti-promemoria': typeof AppRecuperoCreditiPromemoriaRoute
  '/richieste': typeof AppRichiesteRouteWithChildren
  '/scadenziario': typeof AppScadenziarioRoute
  '/template-email': typeof AppTemplateEmailRoute
  '/utenti': typeof AppUtentiRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/firma-privacy/$token': typeof FirmaPrivacyTokenRoute
  '/clienti/$clienteId': typeof AppClientiClienteIdRoute
  '/richieste/$richiestaId': typeof AppRichiesteRichiestaIdRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
  '/api/public/hooks/check-reminder-ritardi': typeof ApiPublicHooksCheckReminderRitardiRoute
  '/api/public/hooks/check-scadenze': typeof ApiPublicHooksCheckScadenzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/approvazioni': typeof AppApprovazioniRoute
  '/assicurazioni': typeof AppAssicurazioniRoute
  '/audit': typeof AppAuditRoute
  '/clienti': typeof AppClientiRouteWithChildren
  '/contatti': typeof AppContattiRoute
  '/dashboard': typeof AppDashboardRoute
  '/fidi-processare': typeof AppFidiProcessareRoute
  '/import-export': typeof AppImportExportRoute
  '/impostazioni': typeof AppImpostazioniRoute
  '/legali': typeof AppLegaliRoute
  '/privacy': typeof AppPrivacyRoute
  '/recupero-crediti': typeof AppRecuperoCreditiRoute
  '/recupero-crediti-andamento': typeof AppRecuperoCreditiAndamentoRoute
  '/recupero-crediti-calendario': typeof AppRecuperoCreditiCalendarioRoute
  '/recupero-crediti-campagne': typeof AppRecuperoCreditiCampagneRoute
  '/recupero-crediti-promemoria': typeof AppRecuperoCreditiPromemoriaRoute
  '/richieste': typeof AppRichiesteRouteWithChildren
  '/scadenziario': typeof AppScadenziarioRoute
  '/template-email': typeof AppTemplateEmailRoute
  '/utenti': typeof AppUtentiRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/firma-privacy/$token': typeof FirmaPrivacyTokenRoute
  '/clienti/$clienteId': typeof AppClientiClienteIdRoute
  '/richieste/$richiestaId': typeof AppRichiesteRichiestaIdRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
  '/api/public/hooks/check-reminder-ritardi': typeof ApiPublicHooksCheckReminderRitardiRoute
  '/api/public/hooks/check-scadenze': typeof ApiPublicHooksCheckScadenzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/approvazioni': typeof AppApprovazioniRoute
  '/_app/assicurazioni': typeof AppAssicurazioniRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/clienti': typeof AppClientiRouteWithChildren
  '/_app/contatti': typeof AppContattiRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fidi-processare': typeof AppFidiProcessareRoute
  '/_app/import-export': typeof AppImportExportRoute
  '/_app/impostazioni': typeof AppImpostazioniRoute
  '/_app/legali': typeof AppLegaliRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/recupero-crediti': typeof AppRecuperoCreditiRoute
  '/_app/recupero-crediti-andamento': typeof AppRecuperoCreditiAndamentoRoute
  '/_app/recupero-crediti-calendario': typeof AppRecuperoCreditiCalendarioRoute
  '/_app/recupero-crediti-campagne': typeof AppRecuperoCreditiCampagneRoute
  '/_app/recupero-crediti-promemoria': typeof AppRecuperoCreditiPromemoriaRoute
  '/_app/richieste': typeof AppRichiesteRouteWithChildren
  '/_app/scadenziario': typeof AppScadenziarioRoute
  '/_app/template-email': typeof AppTemplateEmailRoute
  '/_app/utenti': typeof AppUtentiRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/firma-privacy/$token': typeof FirmaPrivacyTokenRoute
  '/_app/clienti/$clienteId': typeof AppClientiClienteIdRoute
  '/_app/richieste/$richiestaId': typeof AppRichiesteRichiestaIdRoute
  '/api/public/inngest': typeof ApiPublicInngestRoute
  '/api/public/hooks/check-reminder-ritardi': typeof ApiPublicHooksCheckReminderRitardiRoute
  '/api/public/hooks/check-scadenze': typeof ApiPublicHooksCheckScadenzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvazioni'
    | '/assicurazioni'
    | '/audit'
    | '/clienti'
    | '/contatti'
    | '/dashboard'
    | '/fidi-processare'
    | '/import-export'
    | '/impostazioni'
    | '/legali'
    | '/privacy'
    | '/recupero-crediti'
    | '/recupero-crediti-andamento'
    | '/recupero-crediti-calendario'
    | '/recupero-crediti-campagne'
    | '/recupero-crediti-promemoria'
    | '/richieste'
    | '/scadenziario'
    | '/template-email'
    | '/utenti'
    | '/whatsapp'
    | '/firma-privacy/$token'
    | '/clienti/$clienteId'
    | '/richieste/$richiestaId'
    | '/api/public/inngest'
    | '/api/public/hooks/check-reminder-ritardi'
    | '/api/public/hooks/check-scadenze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/approvazioni'
    | '/assicurazioni'
    | '/audit'
    | '/clienti'
    | '/contatti'
    | '/dashboard'
    | '/fidi-processare'
    | '/import-export'
    | '/impostazioni'
    | '/legali'
    | '/privacy'
    | '/recupero-crediti'
    | '/recupero-crediti-andamento'
    | '/recupero-crediti-calendario'
    | '/recupero-crediti-campagne'
    | '/recupero-crediti-promemoria'
    | '/richieste'
    | '/scadenziario'
    | '/template-email'
    | '/utenti'
    | '/whatsapp'
    | '/firma-privacy/$token'
    | '/clienti/$clienteId'
    | '/richieste/$richiestaId'
    | '/api/public/inngest'
    | '/api/public/hooks/check-reminder-ritardi'
    | '/api/public/hooks/check-scadenze'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/approvazioni'
    | '/_app/assicurazioni'
    | '/_app/audit'
    | '/_app/clienti'
    | '/_app/contatti'
    | '/_app/dashboard'
    | '/_app/fidi-processare'
    | '/_app/import-export'
    | '/_app/impostazioni'
    | '/_app/legali'
    | '/_app/privacy'
    | '/_app/recupero-crediti'
    | '/_app/recupero-crediti-andamento'
    | '/_app/recupero-crediti-calendario'
    | '/_app/recupero-crediti-campagne'
    | '/_app/recupero-crediti-promemoria'
    | '/_app/richieste'
    | '/_app/scadenziario'
    | '/_app/template-email'
    | '/_app/utenti'
    | '/_app/whatsapp'
    | '/firma-privacy/$token'
    | '/_app/clienti/$clienteId'
    | '/_app/richieste/$richiestaId'
    | '/api/public/inngest'
    | '/api/public/hooks/check-reminder-ritardi'
    | '/api/public/hooks/check-scadenze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  FirmaPrivacyTokenRoute: typeof FirmaPrivacyTokenRoute
  ApiPublicInngestRoute: typeof ApiPublicInngestRoute
  ApiPublicHooksCheckReminderRitardiRoute: typeof ApiPublicHooksCheckReminderRitardiRoute
  ApiPublicHooksCheckScadenzeRoute: typeof ApiPublicHooksCheckScadenzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firma-privacy/$token': {
      id: '/firma-privacy/$token'
      path: '/firma-privacy/$token'
      fullPath: '/firma-privacy/$token'
      preLoaderRoute: typeof FirmaPrivacyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/utenti': {
      id: '/_app/utenti'
      path: '/utenti'
      fullPath: '/utenti'
      preLoaderRoute: typeof AppUtentiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/template-email': {
      id: '/_app/template-email'
      path: '/template-email'
      fullPath: '/template-email'
      preLoaderRoute: typeof AppTemplateEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scadenziario': {
      id: '/_app/scadenziario'
      path: '/scadenziario'
      fullPath: '/scadenziario'
      preLoaderRoute: typeof AppScadenziarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/richieste': {
      id: '/_app/richieste'
      path: '/richieste'
      fullPath: '/richieste'
      preLoaderRoute: typeof AppRichiesteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recupero-crediti-promemoria': {
      id: '/_app/recupero-crediti-promemoria'
      path: '/recupero-crediti-promemoria'
      fullPath: '/recupero-crediti-promemoria'
      preLoaderRoute: typeof AppRecuperoCreditiPromemoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recupero-crediti-campagne': {
      id: '/_app/recupero-crediti-campagne'
      path: '/recupero-crediti-campagne'
      fullPath: '/recupero-crediti-campagne'
      preLoaderRoute: typeof AppRecuperoCreditiCampagneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recupero-crediti-calendario': {
      id: '/_app/recupero-crediti-calendario'
      path: '/recupero-crediti-calendario'
      fullPath: '/recupero-crediti-calendario'
      preLoaderRoute: typeof AppRecuperoCreditiCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recupero-crediti-andamento': {
      id: '/_app/recupero-crediti-andamento'
      path: '/recupero-crediti-andamento'
      fullPath: '/recupero-crediti-andamento'
      preLoaderRoute: typeof AppRecuperoCreditiAndamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recupero-crediti': {
      id: '/_app/recupero-crediti'
      path: '/recupero-crediti'
      fullPath: '/recupero-crediti'
      preLoaderRoute: typeof AppRecuperoCreditiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legali': {
      id: '/_app/legali'
      path: '/legali'
      fullPath: '/legali'
      preLoaderRoute: typeof AppLegaliRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/impostazioni': {
      id: '/_app/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AppImpostazioniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-export': {
      id: '/_app/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AppImportExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fidi-processare': {
      id: '/_app/fidi-processare'
      path: '/fidi-processare'
      fullPath: '/fidi-processare'
      preLoaderRoute: typeof AppFidiProcessareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatti': {
      id: '/_app/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof AppContattiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clienti': {
      id: '/_app/clienti'
      path: '/clienti'
      fullPath: '/clienti'
      preLoaderRoute: typeof AppClientiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assicurazioni': {
      id: '/_app/assicurazioni'
      path: '/assicurazioni'
      fullPath: '/assicurazioni'
      preLoaderRoute: typeof AppAssicurazioniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvazioni': {
      id: '/_app/approvazioni'
      path: '/approvazioni'
      fullPath: '/approvazioni'
      preLoaderRoute: typeof AppApprovazioniRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/inngest': {
      id: '/api/public/inngest'
      path: '/api/public/inngest'
      fullPath: '/api/public/inngest'
      preLoaderRoute: typeof ApiPublicInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/richieste/$richiestaId': {
      id: '/_app/richieste/$richiestaId'
      path: '/$richiestaId'
      fullPath: '/richieste/$richiestaId'
      preLoaderRoute: typeof AppRichiesteRichiestaIdRouteImport
      parentRoute: typeof AppRichiesteRoute
    }
    '/_app/clienti/$clienteId': {
      id: '/_app/clienti/$clienteId'
      path: '/$clienteId'
      fullPath: '/clienti/$clienteId'
      preLoaderRoute: typeof AppClientiClienteIdRouteImport
      parentRoute: typeof AppClientiRoute
    }
    '/api/public/hooks/check-scadenze': {
      id: '/api/public/hooks/check-scadenze'
      path: '/api/public/hooks/check-scadenze'
      fullPath: '/api/public/hooks/check-scadenze'
      preLoaderRoute: typeof ApiPublicHooksCheckScadenzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-reminder-ritardi': {
      id: '/api/public/hooks/check-reminder-ritardi'
      path: '/api/public/hooks/check-reminder-ritardi'
      fullPath: '/api/public/hooks/check-reminder-ritardi'
      preLoaderRoute: typeof ApiPublicHooksCheckReminderRitardiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppClientiRouteChildren {
  AppClientiClienteIdRoute: typeof AppClientiClienteIdRoute
}

const AppClientiRouteChildren: AppClientiRouteChildren = {
  AppClientiClienteIdRoute: AppClientiClienteIdRoute,
}

const AppClientiRouteWithChildren = AppClientiRoute._addFileChildren(
  AppClientiRouteChildren,
)

interface AppRichiesteRouteChildren {
  AppRichiesteRichiestaIdRoute: typeof AppRichiesteRichiestaIdRoute
}

const AppRichiesteRouteChildren: AppRichiesteRouteChildren = {
  AppRichiesteRichiestaIdRoute: AppRichiesteRichiestaIdRoute,
}

const AppRichiesteRouteWithChildren = AppRichiesteRoute._addFileChildren(
  AppRichiesteRouteChildren,
)

interface AppRouteChildren {
  AppApprovazioniRoute: typeof AppApprovazioniRoute
  AppAssicurazioniRoute: typeof AppAssicurazioniRoute
  AppAuditRoute: typeof AppAuditRoute
  AppClientiRoute: typeof AppClientiRouteWithChildren
  AppContattiRoute: typeof AppContattiRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFidiProcessareRoute: typeof AppFidiProcessareRoute
  AppImportExportRoute: typeof AppImportExportRoute
  AppImpostazioniRoute: typeof AppImpostazioniRoute
  AppLegaliRoute: typeof AppLegaliRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppRecuperoCreditiRoute: typeof AppRecuperoCreditiRoute
  AppRecuperoCreditiAndamentoRoute: typeof AppRecuperoCreditiAndamentoRoute
  AppRecuperoCreditiCalendarioRoute: typeof AppRecuperoCreditiCalendarioRoute
  AppRecuperoCreditiCampagneRoute: typeof AppRecuperoCreditiCampagneRoute
  AppRecuperoCreditiPromemoriaRoute: typeof AppRecuperoCreditiPromemoriaRoute
  AppRichiesteRoute: typeof AppRichiesteRouteWithChildren
  AppScadenziarioRoute: typeof AppScadenziarioRoute
  AppTemplateEmailRoute: typeof AppTemplateEmailRoute
  AppUtentiRoute: typeof AppUtentiRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovazioniRoute: AppApprovazioniRoute,
  AppAssicurazioniRoute: AppAssicurazioniRoute,
  AppAuditRoute: AppAuditRoute,
  AppClientiRoute: AppClientiRouteWithChildren,
  AppContattiRoute: AppContattiRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFidiProcessareRoute: AppFidiProcessareRoute,
  AppImportExportRoute: AppImportExportRoute,
  AppImpostazioniRoute: AppImpostazioniRoute,
  AppLegaliRoute: AppLegaliRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppRecuperoCreditiRoute: AppRecuperoCreditiRoute,
  AppRecuperoCreditiAndamentoRoute: AppRecuperoCreditiAndamentoRoute,
  AppRecuperoCreditiCalendarioRoute: AppRecuperoCreditiCalendarioRoute,
  AppRecuperoCreditiCampagneRoute: AppRecuperoCreditiCampagneRoute,
  AppRecuperoCreditiPromemoriaRoute: AppRecuperoCreditiPromemoriaRoute,
  AppRichiesteRoute: AppRichiesteRouteWithChildren,
  AppScadenziarioRoute: AppScadenziarioRoute,
  AppTemplateEmailRoute: AppTemplateEmailRoute,
  AppUtentiRoute: AppUtentiRoute,
  AppWhatsappRoute: AppWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  FirmaPrivacyTokenRoute: FirmaPrivacyTokenRoute,
  ApiPublicInngestRoute: ApiPublicInngestRoute,
  ApiPublicHooksCheckReminderRitardiRoute:
    ApiPublicHooksCheckReminderRitardiRoute,
  ApiPublicHooksCheckScadenzeRoute: ApiPublicHooksCheckScadenzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
